substitutions:
  device_name: "kellerfenster-vorratsraum"  # only lowercase, numbers, - and _ allowed!
  friendly_name: "Kellerfenster Vorratsraum"
  local_domain: ".fritz.box"


esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: !secret api_encryption

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_keller_ssid
    password: !secret wifi_keller_password

  domain: ".fritz.box"
  use_address: 192.168.178.136

  ap:
    ssid: "${device_name} AP"
    password: !secret hotspot_password

captive_portal:
    


number:
  - platform: template
    id: target_temperature
    name: "Zieltemperatur"
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 16.0
    min_value: 5.0
    max_value: 25.0
    step: 0.5
    unit_of_measurement: "°C"
    mode: slider

  - platform: template
    id: target_humidity
    name: "Zielluftfeuchtigkeit"
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 55.0
    min_value: 20.0
    max_value: 80.0
    step: 1.0
    unit_of_measurement: "%"
    mode: slider

  - platform: template
    id: temperature_hysteresis
    name: "Hysterese Temperatur"
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 0.4
    min_value: 0.0
    max_value: 2.0
    step: 0.2
    unit_of_measurement: "K"
    mode: slider

  - platform: template
    id: humidity_hysteresis
    name: "Hysterese Feuchtigkeit"
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 1.4
    min_value: 0.0
    max_value: 5.0
    step: 0.2
    unit_of_measurement: "%"
    mode: slider

  - platform: template
    id: minimum_time
    name: "Zeit zwischen Aktionen"
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 10
    min_value: 0
    max_value: 60
    step: 1
    unit_of_measurement: "min"
    mode: slider

binary_sensor:
  - platform: status
    name: "Status"

  - platform: gpio
    id: rotary_button
    pin:
      number: GPIO5
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    internal: true
    # on_press:
    #   - logger.log: "Rotary Button Pressed"

  - platform: template
    id: window_request
    name: "Fenster öffnen?"
    lambda: |-
      // Temperature Control
      if (id(inside_temperature_state).state > 0)  // Too warm inside
        return id(outside_temperature_relation).state <= 0; 
      if (id(inside_temperature_state).state < 0)  // Too cold inside
        return id(outside_temperature_relation).state >= 0;
      // Temperature OK -> Humidity Control
      if (id(inside_humidity_state).state > 0)  // Too humid inside
        return id(outside_humidity_relation).state <= 0;
      if (id(inside_humidity_state).state < 0)  // Too dry inside
        return id(outside_humidity_relation).state >= 0;
      // Keep window closed
      return false;

  - platform: template
    id: dehumidify_request
    name: "Luftentfeuchtung erforderlich"
    lambda: |-
      return id(inside_humidity_state).state > 0 &&
             !id(window_request).state;


i2c:
  - id: i2c_inside  # indoor sensor + Display
    sda: GPIO21
    scl: GPIO19
    scan: true
  - id: i2c_outside  # outdoor sensor (separate bus, when sensors having the same id)
    sda: GPIO23
    scl: GPIO22
    scan: true

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    icon: mdi:wifi

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal %"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""
    icon: mdi:wifi

  - platform: aht10
    i2c_id: i2c_inside
    variant: AHT20
    temperature:
      name: "Innentemperatur"
      id: inside_temperature
      device_class: temperature
      state_class: measurement
      accuracy_decimals: 1
    humidity:
      name: "Innenluftfeuchtigkeit"
      id: inside_humidity
      device_class: humidity
      state_class: measurement
      accuracy_decimals: 1
    update_interval: 30s

  - platform: aht10
    i2c_id: i2c_outside
    variant: AHT20
    temperature:
      name: "Außentemperatur"
      id: outside_temperature
      device_class: temperature
      state_class: measurement
      accuracy_decimals: 1
    humidity:
      name: "Außenluftfeuchtigkeit"
      id: outside_humidity
      device_class: humidity
      state_class: measurement
      accuracy_decimals: 1
    update_interval: 30s

  - platform: rotary_encoder
    id: rotary_encoder_1
    pin_a:
      number: GPIO16
      mode:
        input: true
        pullup: true
    pin_b:
      number: GPIO17
      mode:
        input: true
        pullup: true
    resolution: 1
    restore_mode: ALWAYS_ZERO
    internal: true

    on_clockwise:
      - logger.log: "Turned Clockwise"
    on_anticlockwise:
      - logger.log: "Turned Anticlockwise"

  - platform: template
    id: inside_temperature_state
    internal: true
    lambda: |-
      const float t = id(inside_temperature).state;
      const float target = id(target_temperature).state;
      const float h = id(temperature_hysteresis).state / 2.0f;
      if (t >= target + h)
        return 1;  // above target temperature
      if (t <= target - h)
        return -1; // below target temperature
      return 0;    // within target range
    update_interval: 10s

  - platform: template
    id: inside_humidity_state
    internal: true
    lambda: |-
      const float h = id(inside_humidity).state;
      const float target = id(target_humidity).state;
      const float hyst = id(humidity_hysteresis).state / 2.0f;
      if (h >= target + hyst)
        return 1;  // above target humidity
      if (h <= target - hyst)
        return -1; // below target humidity
      return 0;    // within target range
    update_interval: 10s

  - platform: template
    id: outside_temperature_relation
    internal: true
    lambda: |-
      const float h = id(temperature_hysteresis).state / 2.0f;
      if (id(outside_temperature).state >= id(inside_temperature).state + h)
        return 1;  // outside temperature is above inside temperature
      if (id(outside_temperature).state <= id(inside_temperature).state - h)
        return -1; // outside temperature is below inside temperature
      return 0;    // outside temperature is within the hysteresis range
    update_interval: 5s

  - platform: template
    id: outside_humidity_relation
    internal: true
    lambda: |-
      const float h = id(humidity_hysteresis).state / 2.0f;
      if (id(outside_humidity).state >= id(inside_humidity).state + h)
        return 1;  // outside humidity is above inside humidity
      if (id(outside_humidity).state <= id(inside_humidity).state - h)
        return -1; // outside humidity is below inside humidity
      return 0;    // outside humidity is within the hysteresis range
    update_interval: 5s


switch:
  - platform: gpio
    id: relay_open
    pin:
      number: GPIO32  # On-Board Relay 1
      inverted: false
    restore_mode: ALWAYS_OFF
    internal: true
    on_turn_on:
      - switch.turn_off: relay_close

  - platform: gpio
    id: relay_close
    pin:
      number: GPIO33  # On-Board Relay 2
      inverted: false
    restore_mode: ALWAYS_OFF
    internal: true
    on_turn_on:
      - switch.turn_off: relay_open


cover:
  - platform: time_based
    id: window
    name: "Kellerfenster"
    device_class: window

    open_action:
      - switch.turn_off: relay_close
      - switch.turn_on: relay_open

    open_duration: 10s

    close_action:
      - switch.turn_off: relay_open
      - switch.turn_on: relay_close

    close_duration: 10s

    stop_action:
      - switch.turn_off: relay_open
      - switch.turn_off: relay_close


font:
  - file: "gfonts://Roboto"
    id: font_text
    size: 14

  - file: "fonts/materialdesignicons-webfont.ttf"
    id: font_icons
    size: 16
    glyphs:
      - "\U000F0F9C" # mdi:home-import-outline
      - "\U000F0F9B" # mdi:home-export-outline

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    i2c_id: i2c_inside
    address: 0x3C
    update_interval: 1s

    lambda: |-
      // Line 1 - inside
      it.printf(0, 0, id(font_icons), "\U000F0F9C");   // mdi:home-import-outline
      it.printf(22, 0, id(font_text), "%.1f°C / %.1f%%",
                id(inside_temperature).state,
                id(inside_humidity).state);
      // Line 2 - outside
      it.printf(0, 16, id(font_icons), "\U000F0F9B");   // mdi:home-export-outline
      it.printf(22, 16, id(font_text), "%.1f°C / %.1f%%",
                id(outside_temperature).state,
                id(outside_humidity).state);

      // Line 3
      // reserved

      // Line 4
      // reserved